---
- hosts: sasgrid-all
  become: yes
  become_user: root

  tasks:
  - name: start lsf
    shell: ./hostsetup --top="/sas/lsf" --boot="y" --profile="y"  --start="y"
    args:
      chdir: /sas/lsf/10.1/install

- hosts: sasgrid1
  become: yes
  become_user: root

  tasks:
  - name: start jadmin
    shell: |
      . /sas/pm/conf/profile.js;
      jadmin start

  - name: start process manager
    shell:  |
      . /sas/pm/conf/profile.js;
      /sas/pm/10.1/install/bootsetup

  - name: start gms
    shell:  /sas/lsf/gms/bin/gaadmin start
