---
- hosts: sasgridmeta1
  become: yes
  become_user: sasinst

  tasks:
  - name: stop sas services
    shell: |
      . /usr/local/config/Lev1/sas.servers stop

- hosts: sasgridnodes
  become: yes
  become_user: sasinst

  tasks:
  - name: stop sas services
    shell: |
      . /sas/config/Lev1/sas.servers stop
