global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-sas-grid
  regions:
    - us-east-1
    - us-west-1
    - us-west-2
    - eu-west-1
  reporting: true
 
tests:
  quickstart-sas-gridt1:
    parameter_input: sasgrid-quickstart-input-withvpc.json
    template_file: sas-grid-master.template
  quickstart-sas-gridt2:
    parameter_input: sasgrid-quickstart-input-novpc.json
    template_file: sas-grid.template
