---
- hosts: sasgrid1
  become: yes
  become_user: lsfadmin
  vars_files:
    -  /tmp/quickstart/playbooks/vars.yml

  tasks:
  - name: untar pm files
    shell: tar xvf pm10.1_sas_lnx26-x64.tar
    args:
      chdir: /sas/pm_install

  - name: copy license file
    shell: cp  LSF9* /sas/pm_install/pm10.1_sas_pinstall/license.dat
    args:
      chdir: /sas/{{ SASSoftwareDepotName }}/sid_files

  - name: copy config file
    # this file has been seeded with the correct hosts list in hosts.sh
    copy:
      src: /tmp/lsf_install.config
      dest: /sas/pm_install/pm10.1_sas_pinstall/install.config

  - name: make sure the pm subinstall is non-interactive (add -y -s options)
    shell: sed -i.bak 's+\./_jsinstall.*+\./_jsinstall -y -s -f _install.config+' jsinstall
    args:
      chdir: /sas/pm_install/pm10.1_sas_pinstall

- hosts: sasgrid1
  become: yes
  become_user: root
  vars_files:
    -  /tmp/quickstart/playbooks/vars.yml

  tasks:
  - name: Clean lsf directory
    shell: /bin/rm -Rf /sas/lsf

  - name: Clean pm directory
    shell: /bin/rm -Rf /sas/pm

  - name: create directory lsf and set permssions
    file:
      path: /sas/lsf
      state: directory
      owner: lsfadmin
      group: sas
      mode: 0777

  - name: run the install
    shell:  echo 1 | ./jsinstall -f ./install.config &> install.log
    args:
      chdir: /sas/pm_install/pm10.1_sas_pinstall

  - name: create directory lsf/work and set permssions
    file:
      path: /sas/lsf/work
      state: directory
      owner: lsfadmin
      group: sas
      mode: 0777

  - name: create directory lsf/log set permssions
    file:
      path: /sas/lsf/log
      state: directory
      owner: lsfadmin
      group: sas
      mode: 0777

  - name: create directory lsf/temp set permssions
    file:
      path: /sas/lsf/temp
      state: directory
      owner: lsfadmin
      group: sas
      mode: 0777

  - name: replacing a line in lsf.cluster.sas_cluster for sasgrid1
    lineinfile:
      path: /sas/lsf/conf/lsf.cluster.sas_cluster
      regexp: '^(.*)sasgrid1(.*)$'
      line: 'sasgrid1     !     !     1     (mg SASApp)'
      backrefs: yes

  - name: replacing a line in lsf.cluster.sas_cluster for sasgrid2
    lineinfile:
      path: /sas/lsf/conf/lsf.cluster.sas_cluster
      regexp: '^(.*)sasgrid2(.*)$'
      line: 'sasgrid2     !     !     1     (SASApp)'
      backrefs: yes

  - name: replacing a line in lsf.cluster.sas_cluster for sasgrid3
    lineinfile:
      path: /sas/lsf/conf/lsf.cluster.sas_cluster
      regexp: '^(.*)sasgrid3(.*)$'
      line: 'sasgrid3     !     !     1     (SASApp)'
      backrefs: yes

  - name: replacing a line in lsf.cluster.sas_cluster for sasgrid4
    lineinfile:
      path: /sas/lsf/conf/lsf.cluster.sas_cluster
      regexp: '^(.*)sasgrid4(.*)$'
      line: 'sasgrid4     !     !     1     (SASApp)'
      backrefs: yes

- hosts: sasgrid1
  become: yes
  become_user: root

  tasks:

  - name: add lsf startup options
    blockinfile:
      dest:  /sas/lsf/conf/lsf.shared
      marker: '# {mark} add lsf shared options'
      insertbefore: 'End Resource'
      block: |2
            SASApp     Boolean    ()       ()       ()


- hosts: sasgrid-all
  become: yes
  become_user: root

  tasks:

  - name: start lsf
    shell: ./hostsetup --top="/sas/lsf" --boot="y" --profile="y"  --start="y"
    args:
      chdir: /sas/lsf/10.1/install

  - name: add lsf sudoers
    blockinfile:
      dest: /etc/lsf.sudoers
      mode: 600
      create: yes
      marker: '# {mark} add lfs sudoers options'
      insertafter: 'EOF'
      block: |
        LSF_STARTUP_PATH=/sas/lsf/10.1/linux2.6-glibc2.3-x86_64/etc
        LSF_STARTUP_USERS="lsfadmin"



- hosts: sasgrid1
  become: yes
  become_user: root

  tasks:

  - name: start jadmin
    shell: |
      . /sas/pm/conf/profile.js;
      jadmin start

  - name: start process manager
    shell:  |
      . /sas/pm/conf/profile.js;
      /sas/pm/10.1/install/bootsetup

   # GMS
  - name: unzip/untar
    shell: |
      gunzip -d gms8.0.1_install.tar.Z
      tar xvf gms8.0.1_install.tar
    args:
      chdir: /sas/gms_install

  - name: add lsf startup options
    blockinfile:
      dest:  /sas/gms_install/gms8.0.1_install/install.config
      marker: '# {mark} add lsf shared options'
      insertafter: 'EOF'
      block: |
        LSF_TOP=/sas/lsf
        BOOT="Y"

  - name: install gms
    shell: ./gmsinstall -f install.config
    args:
      chdir: /sas/gms_install/gms8.0.1_install

  - name: start gms
    shell:  /sas/lsf/gms/bin/gaadmin start

  - name: change owner of lsf directory and files
    shell: |
      chown -R lsfadmin:sas /sas/lsf

  - name: change owner of pm directory and files
    shell: |
      chown -R lsfadmin:sas /sas/pm
