---
- hosts: sas-all
  gather_facts: no
  become: yes
  become_user: root
  vars_files:
    -  /tmp/quickstart/playbooks/vars.yml

  tasks:

  - name: wait for instances
    wait_for_connection:
      timeout: 3600

  - name: Gathering facts
    setup:

  - name: add all hosts
    blockinfile:
      dest: /etc/hosts
      marker: '# {mark} add all hosts'
      insertafter: 'EOF'
      block:  "{{ lookup('file', '/tmp/extra_hosts') }}"
